version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"
    container_name: softy-pinko-back-end-task5

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"
    container_name: softy-pinko-front-end-task5
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    container_name: softy-pinko-proxy-task5
    depends_on:
      - front-end
      - back-end
